# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         YUM-Config
version:      1.3
version_from: lib/YUM/Config.pm
installdirs:  site
requires:
    File::Remove:                  XML::LibXML
    FreezeThaw:                    Config::IniHash
    Hash::Merge:                   File::Temp
    RPM2:                          LWP::UserAgent
    Sort::Versions:                PerlIO::gzip

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
